services:
  scraper:
    build: .
    container_name: interpol_scrapper
    depends_on:
      - selenium
    networks:
      - my_network
    environment:
      - DISPLAY=host.docker.internal:0.0  # GUI gerektiğinde kullanılır
    deploy:
      resources:
        limits:
          memory: 2g  # Scraper için bellek sınırı
          cpus: "1.0"

  selenium:
    image: selenium/standalone-chrome:4.1.2
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: '4gb'  # Selenium'un daha iyi performans göstermesi için paylaşılan bellek artırıldı
    networks:
      - my_network
    environment:
      - SE_OPENTELEMETRY_ENABLED=false  # OpenTelemetry'yi devre dışı bırakarak performansı artırır
    deploy:
      resources:
        limits:
          memory: 4g  # Selenium için bellek sınırı
          cpus: "2.0"

networks:
  my_network:
    external: true
