# Generated by Django 5.1.1 on 2024-11-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterpolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('img_url', models.URLField(max_length=500)),
            ],
        ),
    ]
