# Generated by Django 5.1.1 on 2024-12-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpol_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpoldata',
            name='name',
        ),
        migrations.AddField(
            model_name='interpoldata',
            name='family_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interpoldata',
            name='forename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interpoldata',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='interpoldata',
            name='img_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interpoldata',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
    ]
